#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Taiki Ikemiyagi
# SPDX-License-Identifier: BSD-3-Clause
import sys
import math


ans = float(sys.argv[1])
def tonum(ans):
    try:
        return int(ans)
    except:
        return float(ans)
    ans=tonum()
print( math.sqrt(ans))
